// GENERATED by webapp/tools/gen_bthome_objects.py -- do not edit. Home Assistant's BTHome
// object table (bthome-ble), so every decoder here walks and names an id the way it does.
export const BTHOME_OBJECTS = {
 "source": "bthome-ble 9449bac22487f4ce15b452c0fdab4638ffb66a8b",
 "objects": {
  "0x00": {
   "name": "packet_id",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x01": {
   "name": "battery",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": "%"
  },
  "0x02": {
   "name": "temperature",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 0.01,
   "unit": "°C"
  },
  "0x03": {
   "name": "humidity",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "%"
  },
  "0x04": {
   "name": "pressure",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.01,
   "unit": "mbar"
  },
  "0x05": {
   "name": "light",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.01,
   "unit": "lx"
  },
  "0x06": {
   "name": "mass",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "kg"
  },
  "0x07": {
   "name": "mass",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "lb"
  },
  "0x08": {
   "name": "dew_point",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 0.01,
   "unit": "°C"
  },
  "0x09": {
   "name": "count",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x0a": {
   "name": "energy",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.001,
   "unit": "kWh"
  },
  "0x0b": {
   "name": "power",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.01,
   "unit": "W"
  },
  "0x0c": {
   "name": "voltage",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.001,
   "unit": "V"
  },
  "0x0d": {
   "name": "pm25",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "µg/m³"
  },
  "0x0e": {
   "name": "pm10",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "µg/m³"
  },
  "0x0f": {
   "name": "generic",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x10": {
   "name": "power_detected",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x11": {
   "name": "opening",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x12": {
   "name": "co2",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "ppm"
  },
  "0x13": {
   "name": "volatile_organic_compounds",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "µg/m³"
  },
  "0x14": {
   "name": "moisture",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "%"
  },
  "0x15": {
   "name": "battery_low",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x16": {
   "name": "battery_charging",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x17": {
   "name": "co",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x18": {
   "name": "cold",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x19": {
   "name": "connectivity",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1a": {
   "name": "door",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1b": {
   "name": "garage_door",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1c": {
   "name": "gas_detected",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1d": {
   "name": "heat",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1e": {
   "name": "light_detected",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x1f": {
   "name": "lock",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x20": {
   "name": "moisture_detected",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x21": {
   "name": "motion",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x22": {
   "name": "moving",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x23": {
   "name": "occupancy",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x24": {
   "name": "plug",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x25": {
   "name": "presence",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x26": {
   "name": "problem",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x27": {
   "name": "running",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x28": {
   "name": "safety",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x29": {
   "name": "smoke",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x2a": {
   "name": "sound",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x2b": {
   "name": "tamper",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x2c": {
   "name": "vibration",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x2d": {
   "name": "window",
   "kind": "binary",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x2e": {
   "name": "humidity",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": "%"
  },
  "0x2f": {
   "name": "moisture",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": "%"
  },
  "0x3a": {
   "name": "button",
   "kind": "event",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x3b": {
   "name": "command",
   "kind": "event",
   "len": null,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x3c": {
   "name": "dimmer",
   "kind": "event",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x3d": {
   "name": "count",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x3e": {
   "name": "count",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x3f": {
   "name": "rotation",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 0.1,
   "unit": "°"
  },
  "0x40": {
   "name": "distance",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1.0,
   "unit": "mm"
  },
  "0x41": {
   "name": "distance",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.1,
   "unit": "m"
  },
  "0x42": {
   "name": "duration",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.001,
   "unit": "s"
  },
  "0x43": {
   "name": "current",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.001,
   "unit": "A"
  },
  "0x44": {
   "name": "speed",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "m/s"
  },
  "0x45": {
   "name": "temperature",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 0.1,
   "unit": "°C"
  },
  "0x46": {
   "name": "uv_index",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 0.1,
   "unit": ""
  },
  "0x47": {
   "name": "volume",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.1,
   "unit": "L"
  },
  "0x48": {
   "name": "volume",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "mL"
  },
  "0x49": {
   "name": "volume_flow_rate",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.001,
   "unit": "m³/h"
  },
  "0x4a": {
   "name": "voltage",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.1,
   "unit": "V"
  },
  "0x4b": {
   "name": "gas",
   "kind": "number",
   "len": 3,
   "signed": false,
   "factor": 0.001,
   "unit": "m³"
  },
  "0x4c": {
   "name": "gas",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 0.001,
   "unit": "m³"
  },
  "0x4d": {
   "name": "energy",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 0.001,
   "unit": "kWh"
  },
  "0x4e": {
   "name": "volume",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 0.001,
   "unit": "L"
  },
  "0x4f": {
   "name": "water",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 0.001,
   "unit": "L"
  },
  "0x50": {
   "name": "timestamp",
   "kind": "timestamp",
   "len": 4,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x51": {
   "name": "acceleration",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.001,
   "unit": "m/s²"
  },
  "0x52": {
   "name": "gyroscope",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.001,
   "unit": "°/s"
  },
  "0x53": {
   "name": "text",
   "kind": "text",
   "len": null,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x54": {
   "name": "raw",
   "kind": "raw",
   "len": null,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x55": {
   "name": "volume_storage",
   "kind": "number",
   "len": 4,
   "signed": false,
   "factor": 0.001,
   "unit": "L"
  },
  "0x56": {
   "name": "conductivity",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "µS/cm"
  },
  "0x57": {
   "name": "temperature",
   "kind": "number",
   "len": 1,
   "signed": true,
   "factor": 1,
   "unit": "°C"
  },
  "0x58": {
   "name": "temperature",
   "kind": "number",
   "len": 1,
   "signed": true,
   "factor": 0.35,
   "unit": "°C"
  },
  "0x59": {
   "name": "count",
   "kind": "number",
   "len": 1,
   "signed": true,
   "factor": 1,
   "unit": ""
  },
  "0x5a": {
   "name": "count",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 1,
   "unit": ""
  },
  "0x5b": {
   "name": "count",
   "kind": "number",
   "len": 4,
   "signed": true,
   "factor": 1,
   "unit": ""
  },
  "0x5c": {
   "name": "power",
   "kind": "number",
   "len": 4,
   "signed": true,
   "factor": 0.01,
   "unit": "W"
  },
  "0x5d": {
   "name": "current",
   "kind": "number",
   "len": 2,
   "signed": true,
   "factor": 0.001,
   "unit": "A"
  },
  "0x5e": {
   "name": "direction",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.01,
   "unit": "°"
  },
  "0x5f": {
   "name": "precipitation",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 0.1,
   "unit": "mm"
  },
  "0x60": {
   "name": "channel",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x61": {
   "name": "rotational_speed",
   "kind": "number",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": "rpm"
  },
  "0x62": {
   "name": "speed",
   "kind": "number",
   "len": 4,
   "signed": true,
   "factor": 1e-06,
   "unit": "m/s"
  },
  "0x63": {
   "name": "acceleration",
   "kind": "number",
   "len": 4,
   "signed": true,
   "factor": 1e-06,
   "unit": "m/s²"
  },
  "0x64": {
   "name": "light_level",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0x65": {
   "name": "settings_revision",
   "kind": "number",
   "len": 1,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0xf0": {
   "name": "device_type_id",
   "kind": "info",
   "len": 2,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0xf1": {
   "name": "firmware_version",
   "kind": "info",
   "len": 4,
   "signed": false,
   "factor": 1,
   "unit": ""
  },
  "0xf2": {
   "name": "firmware_version",
   "kind": "info",
   "len": 3,
   "signed": false,
   "factor": 1,
   "unit": ""
  }
 },
 "events": {
  "button": {
   "0": null,
   "1": "press",
   "2": "double_press",
   "3": "triple_press",
   "4": "long_press",
   "5": "long_double_press",
   "6": "long_triple_press",
   "128": "hold_press"
  },
  "dimmer": {
   "0": null,
   "1": "rotate_left",
   "2": "rotate_right"
  },
  "command": {
   "0": "off",
   "1": "on",
   "2": "toggle",
   "3": "step_up",
   "4": "step_down"
  }
 }
};
